# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180710_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
